language: python
python:
  - "3.6"
install:
- pip install -r requirements.txt
- pip install coveralls
script:
  - nosetests --with-coverage --cover-package=app app/tests

after-success:
  - codecov
  - codecov --token=98be7c9f-8dc8-4497-9845-ce3d503e78ab